In [24]:
import pandas as pd
import numpy as np

In [25]:
"""Pandas offers several methods for handling missing values, primarily represented as NaN (Not a Number)."""
#1. Identifying Missing Values:
#The first step is to identify where missing values exist in your DataFrame or Series.

data = pd.read_csv('retail_product_dataset.csv')

print("This is the dataset of retail product customer reviews")

data.head(10) #The dataset contains NaN that means it has null values

This is the dataset of retail product customer reviews

  Category   Price    Rating         Stock  Discount
0      NaN  5548.0  1.870322           NaN       0.0
1      NaN  3045.0  4.757798           NaN      38.0
2      NaN  4004.0       NaN      In Stock       0.0
3      NaN  4808.0  1.492085           NaN      33.0
4      NaN  1817.0       NaN  Out of Stock      23.0
5      NaN  3522.0       NaN           NaN       NaN
6        C   667.0  3.668341      In Stock      41.0
7        A  7125.0  4.983998  Out of Stock       7.0
8        A  2777.0  2.678384      In Stock       6.0
9      NaN   463.0  4.626187           NaN       3.0

In [26]:
"""Replacing a single value"""
# this will replace "NaN" with "C"
data['Category'] = data['Category'].replace(np.nan, 'C')
data['Category'].head(20)

0     C
1     C
2     C
3     C
4     C
5     C
6     C
7     A
8     A
9     C
10    A
11    A
12    C
13    C
14    B
15    A
16    B
17    C
18    D
19    B
Name: Category, dtype: object

In [27]:
"""replace multiple columns values to one"""
# this will replace "In Stock" and "Out of Stock" with "Stock Limit"
data['Stock'] = data['Stock'].replace(to_replace=["In Stock", "Out of Stock"], value="Stock Limit")
data['Stock'].head(20)

0             NaN
1             NaN
2     Stock Limit
3             NaN
4     Stock Limit
5             NaN
6     Stock Limit
7     Stock Limit
8     Stock Limit
9             NaN
10            NaN
11    Stock Limit
12    Stock Limit
13            NaN
14            NaN
15    Stock Limit
16    Stock Limit
17            NaN
18            NaN
19            NaN
Name: Stock, dtype: object

In [28]:
data['Stock'] = data['Stock'].replace(np.nan,"Within Stock")
data['Stock'].head(20)

0     Within Stock
1     Within Stock
2      Stock Limit
3     Within Stock
4      Stock Limit
5     Within Stock
6      Stock Limit
7      Stock Limit
8      Stock Limit
9     Within Stock
10    Within Stock
11     Stock Limit
12     Stock Limit
13    Within Stock
14    Within Stock
15     Stock Limit
16     Stock Limit
17    Within Stock
18    Within Stock
19    Within Stock
Name: Stock, dtype: object

In [29]:
data['Stock'] = data['Stock'].replace(['Within Stock','Stock Limit'],['In Stock','Out of Limit'])
data['Stock'].head(20)

0         In Stock
1         In Stock
2     Out of Limit
3         In Stock
4     Out of Limit
5         In Stock
6     Out of Limit
7     Out of Limit
8     Out of Limit
9         In Stock
10        In Stock
11    Out of Limit
12    Out of Limit
13        In Stock
14        In Stock
15    Out of Limit
16    Out of Limit
17        In Stock
18        In Stock
19        In Stock
Name: Stock, dtype: object

In [30]:
data.head(5)

  Category   Price    Rating         Stock  Discount
0        C  5548.0  1.870322      In Stock       0.0
1        C  3045.0  4.757798      In Stock      38.0
2        C  4004.0       NaN  Out of Limit       0.0
3        C  4808.0  1.492085      In Stock      33.0
4        C  1817.0       NaN  Out of Limit      23.0

In [31]:
# this will replace "NaN" with "C"
data['Discount'] = data['Discount'].replace(0 , 3.5)
data['Discount'] = data['Discount'].replace(np.nan , 10.0)
data['Discount'].head(20)

0      3.5
1     38.0
2      3.5
3     33.0
4     23.0
5     10.0
6     41.0
7      7.0
8      6.0
9      3.0
10    10.0
11    45.0
12     4.0
13    29.0
14    10.0
15    44.0
16    28.0
17    40.0
18    30.0
19    12.0
Name: Discount, dtype: float64

In [32]:
data['Rating'] = data['Rating'].replace(np.nan, 4.0)
data['Rating'].head(10)

0    1.870322
1    4.757798
2    4.000000
3    1.492085
4    4.000000
5    4.000000
6    3.668341
7    4.983998
8    2.678384
9    4.626187
Name: Rating, dtype: float64

In [33]:
"""Using .astype() for single or multiple columns:"""
# Convert 'Rating' column to integer
data['Rating'] = data['Rating'].astype(int)
data['Rating'].head(10)

0    1
1    4
2    4
3    1
4    4
5    4
6    3
7    4
8    2
9    4
Name: Rating, dtype: int64

In [34]:
data['Discount'] = data['Discount'].astype(int)
data['Discount'].head(10)

0     3
1    38
2     3
3    33
4    23
5    10
6    41
7     7
8     6
9     3
Name: Discount, dtype: int64

In [35]:
data_multi = data.astype({'Discount': int, 'Rating': int})
data_multi.head()

  Category   Price  Rating         Stock  Discount
0        C  5548.0       1      In Stock         3
1        C  3045.0       4      In Stock        38
2        C  4004.0       4  Out of Limit         3
3        C  4808.0       1      In Stock        33
4        C  1817.0       4  Out of Limit        23

In [37]:
#pd.to_numeric(), pd.to_datetime(), pd.to_timedelta()
#converting to numeric, datetime, and timedelta types, respectively, and offer more control over error handling.
data['Stock'] = pd.to_numeric(data['Stock'] , errors='coerce')
data['Stock'].head()

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: Stock, dtype: float64

In [38]:
#str methods
#str.lower() - Convert all strings to lowercase
lower_case_data = data['Category'].str.lower()
lower_case_data.head()

0    c
1    c
2    c
3    c
4    c
Name: Category, dtype: object

In [39]:
#str.upper() - Convert all strings to uppercase
upper_case_data = data['Category'].str.upper()
upper_case_data.head()

0    C
1    C
2    C
3    C
4    C
Name: Category, dtype: object

In [16]:
data.head()

  Category   Price  Rating  Stock  Discount
0        C  5548.0       1    NaN         3
1        C  3045.0       4    NaN        38
2        C  4004.0       4    NaN         3
3        C  4808.0       1    NaN        33
4        C  1817.0       4    NaN        23

In [ ]:
#str.strip() - Remove leading/trailing whitespace
stripped_data = data['Rating'].str.strip()
stripped_data.head()

In [42]:
#str.contains() - Check if a substring is present (returns boolean Series)
contains_stock = data['Category'].str.contains('C')
contains_stock.head(20)

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7     False
8     False
9      True
10    False
11    False
12     True
13     True
14    False
15    False
16    False
17     True
18    False
19    False
Name: Category, dtype: bool

In [43]:
replaced_data = data['Category'].str.replace('D' , 'A')
replaced_data.head(50)

0     C
1     C
2     C
3     C
4     C
5     C
6     C
7     A
8     A
9     C
10    A
11    A
12    C
13    C
14    B
15    A
16    B
17    C
18    A
19    B
20    C
21    C
22    C
23    A
24    C
25    C
26    C
27    A
28    B
29    C
30    C
31    C
32    C
33    C
34    C
35    C
36    A
37    B
38    C
39    C
40    C
41    C
42    C
43    C
44    A
45    C
46    A
47    C
48    C
49    C
Name: Category, dtype: object