In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('student.csv')
data.head(10)

   id         name  class  mark  gender
0   1     John Deo   Four    75  female
1   2     Max Ruin  Three    85    male
2   3       Arnold  Three    55    male
3   4   Krish Star   Four    60  female
4   5    John Mike   Four    60  female
5   6    Alex John   Four    55    male
6   7  My John Rob  Fifth    78    male
7   8       Asruid   Five    85    male
8   9      Tes Qry    Six    78    male
9  10     Big John   Four    55  female

#### Pandas rolling window functions allow you to perform calculations over a specified moving window of data within a Series or DataFrame.
#### This is particularly useful for time series analysis and smoothing data.

1) Define a window: You specify the size of the window (e.g., 3 days, 5 observations).
2) Slide the window: This window slides across your data, one observation at a time.
3) Apply a function: For each position of the window, a specified aggregation function (e.g., mean, sum, min, max, std) is applied to the data within that window.

In [3]:
# Calculate a 3-period rolling mean
data['Rolling_Mean'] = data['mark'].rolling(window=3).mean()
print("DataFrame with Rolling Mean:")
data['Rolling_Mean'].head(20)

DataFrame with Rolling Mean:

0           NaN
1           NaN
2     71.666667
3     66.666667
4     58.333333
5     58.333333
6     64.333333
7     72.666667
8     80.333333
9     72.666667
10    74.000000
11    79.333333
12    90.333333
13    90.000000
14    88.000000
15    88.000000
16    76.666667
17    72.333333
18    49.000000
19    52.666667
Name: Rolling_Mean, dtype: float64

In [4]:

# Calculate a 3-period rolling sum
data['Rolling_Sum'] = data['mark'].rolling(window=4).sum()
print("DataFrame with Rolling Sum:")
data['Rolling_Sum'].head(20)

DataFrame with Rolling Sum:

0       NaN
1       NaN
2       NaN
3     275.0
4     260.0
5     230.0
6     253.0
7     278.0
8     296.0
9     296.0
10    307.0
11    316.0
12    326.0
13    359.0
14    358.0
15    352.0
16    318.0
17    305.0
18    235.0
19    212.0
Name: Rolling_Sum, dtype: float64

In [6]:
# Calculate a 3-period rolling max
data['Rolling_Max'] = data['mark'].rolling(window=3).max()
print("DataFrame with Rolling Max:")
data['Rolling_Max'].head(20)

DataFrame with Rolling Max:

0      NaN
1      NaN
2     85.0
3     85.0
4     60.0
5     60.0
6     78.0
7     85.0
8     85.0
9     85.0
10    89.0
11    94.0
12    94.0
13    94.0
14    88.0
15    88.0
16    88.0
17    88.0
18    75.0
19    75.0
Name: Rolling_Max, dtype: float64

In [8]:
data.head(5)

   id        name  class  mark  gender  Rolling_Mean  Rolling_Sum  Rolling_Max
0   1    John Deo   Four    75  female           NaN          NaN          NaN
1   2    Max Ruin  Three    85    male           NaN          NaN          NaN
2   3      Arnold  Three    55    male     71.666667          NaN         85.0
3   4  Krish Star   Four    60  female     66.666667        275.0         85.0
4   5   John Mike   Four    60  female     58.333333        260.0         60.0

In [ ]:
# Calculate expanding sum
data['expanding_sum'] = data['mark'].expanding().sum()
data['expanding_sum'].head(10)

0     75.0
1    160.0
2    215.0
3    275.0
4    335.0
5    390.0
6    468.0
7    553.0
8    631.0
9    686.0
Name: expanding_sum, dtype: float64

In [ ]:
# Calculate expanding mean
data['expanding_mean'] = data['mark'].expanding().mean()
data['expanding_mean'].head(10)

0    75.000000
1    80.000000
2    71.666667
3    68.750000
4    67.000000
5    65.000000
6    66.857143
7    69.125000
8    70.111111
9    68.600000
Name: expanding_mean, dtype: float64

In [9]:
# Calculate expanding minimum
data['expanding_min'] = data['mark'].expanding().min()
data['expanding_min'].head(10)

0    75.0
1    75.0
2    55.0
3    55.0
4    55.0
5    55.0
6    55.0
7    55.0
8    55.0
9    55.0
Name: expanding_min, dtype: float64

In [ ]:
# Calculate expanding maximum
data['expanding_max'] = data['mark'].expanding().max()
data['expanding_max'].head(10)

0    75.0
1    85.0
2    85.0
3    85.0
4    85.0
5    85.0
6    85.0
7    85.0
8    85.0
9    85.0
Name: expanding_max, dtype: float64

In [12]:
"""The moving average, also known as the rolling mean,
helps reduce noise and highlight significant patterns by averaging data points over a specific window."""
data['EMA_3'] = data['mark'].ewm(span=3, adjust=True).mean() #3-period moving average
data['EMA_3'].head()

0    75.000000
1    81.666667
2    66.428571
3    63.000000
4    61.451613
Name: EMA_3, dtype: float64